name: push-to-another-repo

on: [push]
jobs:
  push-to-another-repo:
    # if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
        # with:
          # node-version: '14'
      - run: echo "making progress"